### ISSUE TITLE
Feature request: transparency for imported STEP models

### ISSUE THREAD

**Issue by jue89** [dune3d/dune3d#122]
For complex assemblies it happens that imported STEP models hide parts of the designed body. It would be nice to specify transparency for STEP models or at least hide them completely.

**Comment by carrotIndustries** [comment]
Encountered that as well. Some thoughts on the implementation: Transparency is fairly hard to implement since currently elements aren't rendered in any particular order. What's possible to implement is hiding the step model entirely or only showing a wireframe.

We could implement this at various levels of granularity and persistence:
 - As a property of the imported STEP model, will be saved in the document
 - As a property of the current group, to be saved in the view state once we have that
 - As a property of the current body, to be saved in the view state once we have that
 - As a property of the current document, to be saved in the view state once we have that

**Comment by jue89** [comment]
> Encountered that as well. Some thoughts on the implementation: Transparency is fairly hard to implement since currently elements aren't rendered in any particular order. What's possible to implement is hiding the step model entirely or only showing a wireframe.

That would help a lot - both. But I'd say its important to keep the selected anchors visible.


> We could implement this at various levels of granularity and persistence:
> 
> * As a property of the imported STEP model, will be saved in the document
> * As a property of the current group, to be saved in the view state once we have that
> * As a property of the current body, to be saved in the view state once we have that
> * As a property of the current document, to be saved in the view state once we have that

In this particular case, I have two step models in one group. I'd love to hide them individually. If the this is saved in the document, I'm completely fine with that.

**Comment by carrotIndustries** [comment]
When selecting a STEP model, there's now an option to hide the solid part of it. Anchors remain visible.

![image](https://github.com/dune3d/dune3d/assets/877304/46ab8fcf-7ee4-4476-99d8-2ee5ffd61069)

So far, it's not saved as all, but will be saved in the view state soon.

**Comment by jue89** [comment]
Thank you a lot! Very nice :)

**Comment by carrotIndustries** [comment]
> So far, it's not saved as all, but will be saved in the view state soon.

Done in eeeca50546caba676ddaaf2dd5c74acc29bad16c.
