### ISSUE TITLE
Pass selected edges to filet / chamfer

### ISSUE THREAD

**Issue by mrlinuxfish** [dune3d/dune3d#64]
It appears all edges for a fillet must be selected after selecting the filet tool instead of using the previously selected edges.

### Actual behaviour
Fillet tool requires edges selected individually after adding a fillet feature

### Expected behaviour
Selected edges are passed to the fillet feature when added. Also, box select is available during selection of edges for a fillet operation

**Comment by carrotIndustries** [comment]
> Selected edges are passed to the fillet feature when added

Unfortunately, that won't work: Fillets/chamfers operate on the solid model generated by opencascade. Tracing the edges from the entities all the way to the final solid model isn't really possible with opencascade as far as I'm aware. That's why there is the select edges tool.

If someone knows differently, please let me know.
